apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::887363634632:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-LuzaIozbKs78
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: aarn:aws:iam::887363634632:user/Rajesh
      username: Rajesh 
      groups:
        - rajesh-trainee



